version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - '.*\.Close$'
      - '.*\.SetReadDeadline$'
      - '.*\.SetWriteDeadline$'
      - '.*\.Rollback$'
      - '.*\.Release$'
  dupl:
    threshold: 140
  exhaustive:
    check:
      - switch
      - map
  gosec:
    excludes:
      - G101
      - G115
      - G306
      - G401
      - G404
      - G505
  misspell:
    locale: US
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

