name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FITZ_BROKER_ANON_TCP_ADDR: localhost:4191
      FITZ_BROKER_ANON_WS_ADDR: ws://localhost:4190/ws
      FITZ_BROKER_AUTH_TCP_ADDR: localhost:4091
      FITZ_BROKER_AUTH_WS_ADDR: ws://localhost:4090/ws
      FITZ_BROKER_JWT_HMAC_SECRET: test-secret-key
      FITZ_BROKER_JWT_AUDIENCE: fitz
    steps:
      - name: Check out fitz-ts
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.6"

      - name: Install dependencies
        run: go mod download

      - name: Run lint
        run: go vet ./...

      - name: Run build
        run: go build ./...

      # - name: Start broker stack
      #   if: always()
      #   run: docker compose up -d

      # - name: Run tests
      #   run: go test ./... -v --cover

      # - name: Stop broker stack
      #   if: always()
      #   run: docker compose down --volumes
